### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by andreabedini**
#### What does this PR do?

Hi there,

I thought it would be a good idea to replace Travis CI with GitHub Actions. See the post by Emily Pillmore on [/r/haskell](https://www.reddit.com/r/haskell/comments/jvbs49/psa_maintainers_should_think_about_migrating_off/).

I only managed to test it locally because apparently GitHub doens't seem to run actions on forks. I wonder if it will run on this RP.

### CODE REVIEW

**Comment by hverr** [comment]
Happy to land this if this works. I am completely unfamiliar with GitHub actions though, tell me if you need help testing this.

**Comment by andreabedini** [comment]
Hi @hverr, you might need to tick some boxes before GitHub runs the workflow I have included, see https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/. 

Otherwise I can restore the travis ci bits, merge the GitHub actions bits and let it run. (Perhaps on a separate branch so we don't mess up master too much trying to get the CI to work)

**Comment by hverr** [comment]
I've added you as a maintainer to the project. I've also enabled Actions in the projects settings. Feel free to do all the experimentation you want and push the final version to master if you are confident it's working :)

**Comment by andreabedini** [comment]
Thanks @hverr !

**Comment by andreabedini** [comment]
I think I'll have to work in a branch to test it. I will be working in `github-actions`. I'm closing and I will reopen a PR when ready.

**Pull request closed without merging**
